apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
spec: 
  replicas: 1
  selector:
    matchLabels:
      component: notifications-api
  template:
    metadata:
      labels:
        component: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: purpler1/notifications-api
          ports:
            - containerPort: 5001