apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      component: product-api
  template:
    metadata:
      labels:
        component: product-api
    spec:
      containers:
      - name: product-api
        image: purpler1/products-api:v2
        ports:
          - containerPort: 5002 
        env:
          - name: MONGODB_HOST
            value: "mongodb-cluster-ip-service"
        envFrom:
          - configMapRef:
              name: rabbitmq-configmap
